# yaml-language-server: $schema=https://raw.githubusercontent.com/cncf/landscape2/refs/heads/main/docs/config/schema/settings.schema.json

# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: Bundesverband Green Software

url: https://landscape.bundesverband-green-software.de

# BVGS Colors:
# - green:      rgba(0, 150, 79, 1)
# - dark green: rgba(0, 112, 58, 1)
# - yellow:     rgba(255, 206, 68, 1)
# - red:        rgba(227, 6, 19, 1)
# - black:      rgba(29, 29, 27, 1)

colors:
  color1: "rgba(0, 150, 79, 1)" # Buttons, groups, links
  color2: "rgba(227, 6, 19, 1)" # Some highlighted items like filters button, search icon
  color3: "rgba(255, 206, 68, 1)" # Participation stats bars, spinners, modal titles
  color4: "rgba(29, 29, 27, 1)" # Categories titles in filters, fieldset in filters modal
  color5: "rgba(0, 112, 58, 1)" # Categories and subcategories frames (odd)
  color6: "rgba(0, 150, 79, 1)" # Categories and subcategories frames (even)
  color7: "rgba(0, 150, 79, 1)" # Borders, shadows and options boxes in games

description: The landscape provides an overview of the green software tool ecosystem

featured_items:
  - field: maturity
    options:
      - value: in-active-use-by-members
        order: 1
        label: In Active Use by BvGS Members

footer:
  links:
    homepage: https://www.bundesverband-green-software.de
    linkedin: https://www.linkedin.com/company/bundesverband-green-software/
    github: https://github.com/bundesverband-green-software/
  logo: https://raw.githubusercontent.com/bundesverband-green-software/landscape/refs/heads/main/logos/bvgs/logo-bvgs-white.svg
  text: |
    Copyright © 2025 Bundesverband Green Software

grid_items_size: large

groups:
  - name: Measurement
    categories:
      - Infrastructure & Cluster Level
      - Component
      - Website
      - Artificial Intelligence
      - Code
      - Databases
      - Data Aggregation
      - Measurement Toolbox
  - name: Optimization
    categories:
      - Optimization

header:
  links:
    github: https://github.com/bundesverband-green-software/landscape
  logo: https://raw.githubusercontent.com/bundesverband-green-software/landscape/refs/heads/main/logos/bvgs/logo-bvgs.svg

images:
  favicon: https://www.bundesverband-green-software.de/favicon-96x96.png

screenshot_width: 1600
