name: Tool Proposal
description: Use this template to propose a new tool.
title: "[Tool Proposal]: "
labels: ["tool proposal"]
body:
  - type: markdown
    attributes:
      value: |
        
        Thanks for taking the time to propose adding a missing tool to the landscape!

  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the tool

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of what the tool does

  - type: textarea
    id: urls
    attributes:
      label: URLs
      description: URLs to the home page, repository, docs, etc.

  - type: input
    id: logo
    attributes:
      label: Logo
      description: Path to logo (optional)

  - type: dropdown
    id: categories_measurement
    attributes:
      label: In which measurement categories should the tool be listed? (multiple ones can be selected)
      multiple: true
      options:
        - Infrastructure - Provider Level
        - Infrastructure - Kubernetes
        - Infrastructure - Other
        - Containerized Applications
        - Framework
        - Mobile App
        - Code
        - AI Model Training
        - AI Inference
        - Carbon Intensity (Data Provider)
        - Emission Inventory (Data Provider)
        - IT Inventory / Organizational Level (Data Aggregation)
        - Desktop
        - Shell
        - CI Pipeline
        - Website Carbon Estimation
        - Website Energy Measurement
        - Browser Extensions

  - type: dropdown
    id: categories_optimization
    attributes:
      label: In which optimization categories should the tool be listed? (multiple ones can be selected)
      multiple: true
      options:
        - Cloud Infrastructure
        - Cloud Application Profiling
        - Kubernetes
        - Carbon Awareness
        - Static Code Analysis
        - Artificial Intelligence

  - type: input
    id: categories_missing
    attributes:
      label: Are categories missing?

  - type: markdown
    attributes:
      value: |
        
        *Please also answer the following questions to help us decide whether the tool is appropriate for the landscape.*
  
  - type: textarea
    id: comparison_to_others
    attributes:
      label: What does the tool do and what are the advantages compared to similar tools?

  - type: textarea
    id: methodology
    attributes:
      label: Where is the methodology of the tool described in detail?** (Should be publicly accessible)

  - type: textarea
    id: integration
    attributes:
      label: How can the tool be used and integrated into the software lifecycle?
