name: Tool Proposal
description: Use this template to propose a new tool.
title: "[Tool Proposal]: "
labels: ["tool proposal"]
body:
  - type: markdown
    attributes:
      value: |
        
        Thanks for taking the time to propose adding a new tool to the landscape!

  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the tool
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of what the tool does
    validations:
      required: true

  - type: textarea
    id: urls
    attributes:
      label: URLs
      description: URLs to the home page, repository, docs, etc.
    validations:
      required: true

  - type: input
    id: logo
    attributes:
      label: Logo
      description: Path to logo (optional)

  - type: dropdown
    id: categories_measurement
    attributes:
      label: In which measurement categories should the tool be listed? (multiple ones can be selected)
      multiple: true
      options:
        - Public Cloud
        - Kubernetes
        - On-Premise & Bare-Metal
        - Containerized Application
        - Desktop Application
        - Mobile App
        - Device & Process Level
        - Code Level Energy Measurement
        - Static Code Analysis
        - CI Pipeline
        - Website Carbon Estimation
        - Website Energy Measurement
        - Website Profiling
        - AI Model Training
        - AI Inference
        - Grid Carbon Intensity API Service
        - IT Emission Inventory
        - Data Aggregation - Organizational Level
        - Data Aggregation - Estimation
        - Data Aggregation - Modeling
        - Measurement Utilities

  - type: dropdown
    id: categories_optimization
    attributes:
      label: In which optimization categories should the tool be listed? (multiple ones can be selected)
      multiple: true
      options:
        - Cloud Infrastructure
        - Cloud Application Analysis
        - Kubernetes
        - Carbon Awareness
        - Artificial Intelligence
        - CI/CD Pipeline

  - type: input
    id: categories_missing
    attributes:
      label: Are categories missing?

  - type: markdown
    attributes:
      value: |
        
        *Please also answer the following questions to help us decide whether the tool is appropriate for the landscape.*

  - type: dropdown
    attributes:
      label: Status
      description: What status does the tool/project currently have?
      multiple: false
      options:
        - Concept
        - In early development
        - Beta
        - Stable / Mature
        - Deprecated / Archived (not supported anymore)
    validations:
      required: true

  - type: textarea
    id: comparison_to_others
    attributes:
      label: What does the tool do and what are the advantages compared to similar tools?

  - type: textarea
    id: methodology
    attributes:
      label: Where is the methodology of the tool described in detail? (Should be publicly accessible)
  
  - type: textarea
    id: integration
    attributes:
      label: In which phases of the software lifecycle (Design, Development, Testing, Usage, Removal) can the tool be used, and how can it be integrated / set up?
