name: Tool Proposal
description: Use this template to propose a new tool.
title: "[Tool Proposal]: "
labels: ["tool proposal"]
body:
  - type: markdown
    attributes:
      value: |
        
        Thanks for taking the time to propose adding a new tool to the landscape!

  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the tool
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of what the tool does
    validations:
      required: true

  - type: textarea
    id: urls
    attributes:
      label: URLs
      description: URLs to the home page, repository, docs, etc.
    validations:
      required: true

  - type: input
    id: logo
    attributes:
      label: Logo
      description: Path to logo (optional)

  - type: dropdown
    id: categories_measurement
    attributes:
      label: "In which measurement categories should the tool be listed? (multiple ones can be selected)"
      multiple: true
      options:
        - Infrastructure Provider Level
        - Kubernetes
        - Agent
        - Containerized Application
        - Desktop Application
        - Mobile App
        - Device & Process Level
        - Code Level Energy Measurement
        - Static Code Analysis
        - CI Pipeline
        - Website Carbon Estimation
        - Website Energy Measurement
        - Website Profiling
        - AI Model Training
        - AI Inference
        - Grid Carbon Intensity API Service
        - IT Emission Inventory
        - Data Aggregation - Organizational Level
        - Data Aggregation - Estimation
        - Data Aggregation - Modeling
        - Measurement Utilities

  - type: dropdown
    id: categories_optimization
    attributes:
      label: "In which optimization categories should the tool be listed? (multiple ones can be selected)"
      multiple: true
      options:
        - Cloud Infrastructure
        - Cloud Application Analysis
        - Kubernetes
        - Carbon Awareness
        - Artificial Intelligence
        - CI/CD Pipeline

  - type: input
    id: categories_missing
    attributes:
      label: Are categories missing?

  - type: markdown
    attributes:
      value: |
        
        *Please also answer the following questions to help us decide whether the tool is appropriate for the landscape.*

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: "What status does the tool/project currently have?"
      multiple: false
      options:
        - Concept
        - In early development
        - Beta
        - Stable / Mature
        - Deprecated / Archived (not supported anymore)
    validations:
      required: true

  - type: textarea
    id: comparison_to_others
    attributes:
      label: "What does the tool do and what are the advantages compared to similar tools?"
    validations:
      required: true

  - type: dropdown
    id: metrics
    attributes:
      label: "If it is a measurement tool: Which metrics does the tool output? (multiple ones can be selected)"
      multiple: true
      options:
        - Energy
        - Embodied Carbon Emissions
        - Operational Carbon Emissions
        - Grid Carbon Intensity
        - Water Use
        - Electronic Waste
        - Toxicity
        - Abiotic Depletion Potential (ADP)
        - Biodiversity Loss
        - Others
    validations:
      required: true

  - type: dropdown
    id: grid_intensity_method
    attributes:
      label: "If carbon emissions are calculated: Which grid intensity method does the tool use?"
      multiple: true
      options:
        - Market Based
        - Location Based
    validations:
      required: true

  - type: dropdown
    id: emission_scopes
    attributes:
      label: "If carbon emissions are calculated: Which emission scopes are covered by the tool?"
      multiple: true
      options:
        - Scope 1
        - Scope 2
        - Scope 3
    validations:
      required: true

  - type: dropdown
    id: direct_or_model
    attributes:
      label: "If it is a measurement tool: Is the tool using direct measurement or model based measurement?"
      multiple: true
      options:
        - Direct
        - Model Based
    validations:
      required: true

  - type: textarea
    id: direct_measurement_method
    attributes:
      label: "If the tool uses a direct measurement approach: What hardware devices, software power meters and configuration are used?"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        
        Example: We are using RAPL to get the CPU energy with 100ms sampling rate
        Example #2: We are using a Xilinx power meter which captures all three AC phases of the rack and then split by 10 to get the power per VM

  - type: textarea
    id: model_source_data
    attributes:
      label: "If the tool uses uses a model-based approach: Please disclose which source data were used as input data (separate for every model)"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        Example: We use an XGBoost Model to get from CPU Utilization to Energy consumption based on average data from the TEADS Open Dataset of AWS Energy Measurements
        Example #2: We get embodied carbon values from the ADEME database

  - type: dropdown
    id: integration
    attributes:
      label: "In which phases of the software lifecycle can the tool be used?"
      multiple: true
      options:
        - Design
        - Development
        - Testing
        - Usage / Production
        - Removal
    validations:
      required: false
