name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      labels: ubuntu-latest
    container:
      image: public.ecr.aws/g6m3a0y9/landscape2
      options: --user root
    steps:
      - name: Install git
        run: apk add git

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install tar in container (needed for the cache)
        run: apk add --update --no-progress tar

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: /tmp/landscape-cache
          key: landscape-cache-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            landscape-cache-

      - name: Build landscape
        env:
          GITHUB_TOKENS: ${{ secrets.GH_TOKENS }}
        run: |
          landscape2 build \
            --settings-file ./settings.yml \
            --guide-file ./guide.yml \
            --data-file ./data.yml \
            --logos-path ./logos \
            --cache-dir /tmp/landscape-cache \
            --output-dir /tmp/landscape

      - name: Commit built landscape to build branch
        run: |
          git config --global safe.directory `pwd`
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@users.noreply.github.com"
          git fetch origin build:build
          git checkout build
          git branch --set-upstream-to=origin/build build
          git pull
          # Remove all except the CNAME file
          find . ! -name 'CNAME' -exec rm -rf {} +
          cp -R /tmp/landscape/* .
          cp index.html 404.html
          git add .
          git commit -m "Build landscape"
          git push origin build
