name: Build using landscape2 & Deploy with GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '*.yml'
      - 'logos/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on:
      labels: ubuntu-latest
    container:
      image: public.ecr.aws/g6m3a0y9/landscape2
      options: --user root
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install tar in container (needed for the cache)
        run: apk add --update --no-progress tar

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: cache
          key: landscape-cache-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            landscape-cache-

      - name: Build landscape
        env:
          GITHUB_TOKENS: ${{ secrets.GITHUB_TOKEN }} # 'GITHUB_TOKENS' is used by landscape2
        run: |
          landscape2 build \
            --settings-file ./settings.yml \
            --guide-file ./guide.yml \
            --data-file ./data.yml \
            --logos-path ./logos \
            --cache-dir cache \
            --output-dir build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
